spring.ai.openai.base-url=https://dashscope.aliyuncs.com/compatible-mode/v1
spring.ai.openai.api-key=${DASHSCOPE_API_KEY}

spring.ai.openai.chat.completions-path=/chat/completions
spring.ai.openai.chat.options.model=qwen-turbo
spring.ai.openai.chat.options.temperature=0.6

spring.ai.openai.embedding.embeddings-path=/embeddings
spring.ai.openai.embedding.options.model=text-embedding-v2

spring.ai.vectorstore.redis.initialize-schema=true
spring.ai.vectorstore.redis.index-name=spring-ai-index-v2

logging.level.org.springframework.ai.chat.client.advisor=DEBUG
